version: '3.7'
services:
  database:
    build:
    context: ./database
    ports:
      - 3306:3306
    container_name: database-container 
  backend:
    build:
    context: ./backend-cms
    container_name: backendcms-container 
    ports:
      - 3002:3002
    links:
        - database
