version: '3.7'
services:
  database:
    #env_file: database/env.list
    build: database
    image: "sam/database:1.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    container_name: database-container
    hostname: mysqldatabase
    networks:
      - nw_dockerapp
    # volumes:
    #   - ./database:/var/usr/ 
  backend:
    build: backendcms
    image: "sam/backendcms:1.0"
    container_name: backendcms-container
    # volumes:
    #   - ./backend:/usr/src/app
    ports:
      - 3000:3000
    links:
        - database
    depends_on:
      - database
    networks:
      - nw_dockerapp
      #  ipv4_address: 10.5.0.6
        
  frontend:
    build: react-frontend
    image: "sam/react-frontend:1.0"
    container_name: react-frontend-container
    # volumes:
    #   - ./react-frontend:/usr/src/react-app
    ports:
      - 4000:3000
    depends_on:
      - database
      - backend
    networks:
      - nw_dockerapp
      #  ipv4_address: 10.5.0.7
networks:
  nw_dockerapp: 
      driver: bridge 